services:
  zstart_postgres:
    image: mooncakelabs/pg_mooncake:latest
    shm_size: 1g
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      DUCKDB_FORCE_EXECUTION: ${DUCKDB_FORCE_EXECUTION:-off}
    volumes:
      - zstart_pgdata:/var/lib/postgresql
      - /Users/yo_macbook/Documents/app_data:/app_data:ro
      - ./init/01-setup-extensions.sql:/docker-entrypoint-initdb.d/01-setup-extensions.sql:ro
      - ./init/02-create-app-roles.sql:/docker-entrypoint-initdb.d/02-create-app-roles.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/03-seed.sql:ro

volumes:
  zstart_pgdata:
    driver: local
